#include "/Engine/Public/Platform.ush"

RWStructuredBuffer<float3> PositionBuffer;
RWStructuredBuffer<float3> TangentsBuffer;

StructuredBuffer<float4x4> BoneMatrices;
StructuredBuffer<float4> BoneIndicesBuffer;
StructuredBuffer<float4> BoneWeightsBuffer;
StructuredBuffer<uint> IndirectArgsBuffer;

int NumMatrix;

[numthreads(256,1,1)]
void MainCS(uint3 DTid : SV_DispatchThreadID)
{
	int vid = DTid.x;
    if (vid >= IndirectArgsBuffer[0])
    {
	    return;
    }
	
	uint4 boneIndices = (uint4)(BoneIndicesBuffer[vid] * 255.5f);
	float4 boneWeights = BoneWeightsBuffer[vid];
	
	uint TBase = vid * 2;
	
	float3 position = float3(0,0,0);
	float3 tangent = float3(0,0,0);
	float3 normal = float3(0,0,0);
	for (int i =0; i<4;++i)
	{
		float4x4 M = BoneMatrices[boneIndices[i]];
		position += mul(float4(PositionBuffer[vid], 1), M).xyz * boneWeights[i];
		tangent += mul(float4(TangentsBuffer[TBase + 0], 0), M).xyz * boneWeights[i];
		normal += mul(float4(TangentsBuffer[TBase + 1], 0), M).xyz * boneWeights[i];
	}
    PositionBuffer[vid] = position;
    TangentsBuffer[TBase + 0] = tangent;
    TangentsBuffer[TBase + 1] = normal;
}