#include "/Engine/Public/Platform.ush"

RWStructuredBuffer<float3> PositionBuffer;
RWStructuredBuffer<float3> TangentsBuffer;

StructuredBuffer<float4x4> BoneMatrices;
StructuredBuffer<uint> BoneIndicesBuffer;
StructuredBuffer<uint> IndirectArgsBuffer;

int NumMatrix;

[numthreads(256,1,1)]
void MainCS(uint3 DTid : SV_DispatchThreadID)
{
	int vid = DTid.x;
    if (vid >= IndirectArgsBuffer[0])
    {
	    return;
    }
	uint bone = BoneIndicesBuffer[vid];

	float4x4 M = BoneMatrices[bone];
    PositionBuffer[vid] = mul(float4(PositionBuffer[vid], 1), M).xyz;
	
	uint TBase = vid * 2;

	float3 T = TangentsBuffer[TBase + 0];
	float3 N = TangentsBuffer[TBase + 1];

	TangentsBuffer[TBase + 0] = normalize(mul(float4(T, 0), M).xyz);
	TangentsBuffer[TBase + 1] = normalize(mul(float4(N, 0), M).xyz);
}