#include "TimeThiefSmokeRendererTypes.h"

namespace
{
	FVector3f ToVector3f(const FVector& Value)
	{
		return FVector3f(static_cast<float>(Value.X), static_cast<float>(Value.Y), static_cast<float>(Value.Z));
	}

	FVector3f GetDefaultRenderBoundsExtent()
	{
		return ToVector3f(TimeThiefSmokeParameterDefaults::GetSmokeBoundsExtent() + TimeThiefSmokeParameterDefaults::GetRenderBoundsPadding());
	}
}

FTimeThiefSmokeRendererSettings::FTimeThiefSmokeRendererSettings()
	: SimulationBackend(ETimeThiefSmokeSimulationBackend::SparseMac)
	, PressureSolver(TimeThiefSmokeParameterDefaults::bUseMultigridPressureByDefault ? ETimeThiefSmokePressureSolver::Multigrid : ETimeThiefSmokePressureSolver::JacobiLegacy)
	, SmokeGridResolution(TimeThiefSmokeParameterDefaults::SmokeGridResolution)
	, PressureIterations(TimeThiefSmokeParameterDefaults::PressureIterations)
	, RenderStepCount(TimeThiefSmokeParameterDefaults::RenderStepCount)
	, SmokeBrickSize(TimeThiefSmokeParameterDefaults::SmokeBrickSize)
	, MaxActiveSmokeBricks(TimeThiefSmokeParameterDefaults::MaxActiveSmokeBricks)
	, RenderMaxStepCount(TimeThiefSmokeParameterDefaults::RenderMaxStepCount)
	, RenderStepVoxelScale(TimeThiefSmokeParameterDefaults::RenderStepVoxelScale)
	, MaxGPUEventsPerSmokePerFrame(TimeThiefSmokeParameterDefaults::MaxGPUEventsPerSmokePerFrame)
	, InitialDensity(TimeThiefSmokeParameterDefaults::InitialDensity)
	, SmokeFadeOutDuration(TimeThiefSmokeParameterDefaults::SmokeFadeOutDuration)
	, PlumeEmissionDuration(TimeThiefSmokeParameterDefaults::PlumeEmissionDuration)
	, PlumeSourceRadius(TimeThiefSmokeParameterDefaults::PlumeSourceRadius)
	, ObstacleSourceClearRadiusScale(TimeThiefSmokeParameterDefaults::ObstacleSourceClearRadiusScale)
	, PlumeExpansionVelocity(TimeThiefSmokeParameterDefaults::PlumeExpansionVelocity)
	, PlumeRiseVelocity(TimeThiefSmokeParameterDefaults::PlumeRiseVelocity)
	, Extinction(TimeThiefSmokeParameterDefaults::Extinction)
	, ScatteringAlbedo(TimeThiefSmokeParameterDefaults::ScatteringAlbedo)
	, ScatteringAnisotropy(TimeThiefSmokeParameterDefaults::ScatteringAnisotropy)
	, DensityDissipation(TimeThiefSmokeParameterDefaults::DensityDissipation)
	, VelocityDamping(TimeThiefSmokeParameterDefaults::VelocityDamping)
	, VorticityStrength(TimeThiefSmokeParameterDefaults::VorticityStrength)
	, VorticityConfinementStrength(TimeThiefSmokeParameterDefaults::VorticityConfinementStrength)
	, TurbulenceStrength(TimeThiefSmokeParameterDefaults::TurbulenceStrength)
	, AirInteractionStrength(TimeThiefSmokeParameterDefaults::AirInteractionStrength)
	, SelfWobbleTimeScale(TimeThiefSmokeParameterDefaults::SelfWobbleTimeScale)
	, SelfWobbleVelocityScale(TimeThiefSmokeParameterDefaults::SelfWobbleVelocityScale)
	, SelfWobbleForceScale(TimeThiefSmokeParameterDefaults::SelfWobbleForceScale)
	, SelfWobbleParticleScale(TimeThiefSmokeParameterDefaults::SelfWobbleParticleScale)
	, EventVortexStrength(TimeThiefSmokeParameterDefaults::EventVortexStrength)
	, VortexParticleCount(TimeThiefSmokeParameterDefaults::VortexParticleCount)
	, VortexParticleLifeSeconds(TimeThiefSmokeParameterDefaults::VortexParticleLifeSeconds)
	, VortexParticleStrength(TimeThiefSmokeParameterDefaults::VortexParticleStrength)
	, VortexParticleSplatRadius(TimeThiefSmokeParameterDefaults::VortexParticleSplatRadius)
	, VortexParticleCoreRadius(TimeThiefSmokeParameterDefaults::VortexParticleCoreRadius)
	, VortexDensityGradientScale(TimeThiefSmokeParameterDefaults::VortexDensityGradientScale)
	, WarpTrailIntensity(TimeThiefSmokeParameterDefaults::WarpTrailIntensity)
	, WarpTrailDecayRate(TimeThiefSmokeParameterDefaults::WarpTrailDecayRate)
	, WarpTrailRadiusScale(TimeThiefSmokeParameterDefaults::WarpTrailRadiusScale)
	, WarpTrailLengthScale(TimeThiefSmokeParameterDefaults::WarpTrailLengthScale)
	, ActorWarpDensityAccumulationScale(TimeThiefSmokeParameterDefaults::ActorWarpDensityAccumulationScale)
	, ActorWarpAccumulationDecaySeconds(TimeThiefSmokeParameterDefaults::ActorWarpAccumulationDecaySeconds)
	, ActorWarpEmissionRemainder(TimeThiefSmokeParameterDefaults::ActorWarpEmissionRemainder)
	, ActorAirflowStrength(TimeThiefSmokeParameterDefaults::ActorAirflowStrength)
	, ActorAirflowMinSpeed(TimeThiefSmokeParameterDefaults::ActorAirflowMinSpeed)
	, ActorAirflowFullSpeed(TimeThiefSmokeParameterDefaults::ActorAirflowFullSpeed)
	, ActorAirflowRadiusScale(TimeThiefSmokeParameterDefaults::ActorAirflowRadiusScale)
	, ActorAirflowFrontStrength(TimeThiefSmokeParameterDefaults::ActorAirflowFrontStrength)
	, ActorAirflowSideStrength(TimeThiefSmokeParameterDefaults::ActorAirflowSideStrength)
	, ActorAirflowWakeStrength(TimeThiefSmokeParameterDefaults::ActorAirflowWakeStrength)
	, ActorAirflowVortexStrength(TimeThiefSmokeParameterDefaults::ActorAirflowVortexStrength)
	, SparseVelocityActiveThreshold(TimeThiefSmokeParameterDefaults::SparseVelocityActiveThreshold)
	, BulletWakeMaxVisibleLife(TimeThiefSmokeParameterDefaults::BulletWakeMaxVisibleLife)
	, BulletWakeReleaseDuration(TimeThiefSmokeParameterDefaults::BulletWakeReleaseDuration)
	, BulletWakeSinkLife(TimeThiefSmokeParameterDefaults::BulletWakeSinkLife)
	, BulletWakeSinkStrength(TimeThiefSmokeParameterDefaults::BulletWakeSinkStrength)
	, BulletWakeImpulseStrength(TimeThiefSmokeParameterDefaults::BulletWakeImpulseStrength)
	, BulletWakeCutoutFeather(TimeThiefSmokeParameterDefaults::BulletWakeCutoutFeather)
	, bUseMacCormackAdvection(TimeThiefSmokeParameterDefaults::bUseMacCormackAdvection)
	, bUseAdaptiveMacCormack(TimeThiefSmokeParameterDefaults::bUseAdaptiveMacCormack)
	, bUseVortexBrickBins(TimeThiefSmokeParameterDefaults::bUseVortexBrickBins)
	, RenderNoiseScale(TimeThiefSmokeParameterDefaults::RenderNoiseScale)
	, RenderNoiseStrength(TimeThiefSmokeParameterDefaults::RenderNoiseStrength)
	, RenderNoiseTimeScale(TimeThiefSmokeParameterDefaults::RenderNoiseTimeScale)
	, RenderFilamentScale(TimeThiefSmokeParameterDefaults::RenderFilamentScale)
	, RenderFilamentStrength(TimeThiefSmokeParameterDefaults::RenderFilamentStrength)
	, RenderFilamentContrast(TimeThiefSmokeParameterDefaults::RenderFilamentContrast)
	, RenderFilamentWarpStrength(TimeThiefSmokeParameterDefaults::RenderFilamentWarpStrength)
{
}

FTimeThiefSmokeRendererVolume::FTimeThiefSmokeRendererVolume()
	: BoundsExtent(GetDefaultRenderBoundsExtent())
	, SimulationBoundsExtent(GetDefaultRenderBoundsExtent())
	, NaturalBoundsExtent(ToVector3f(TimeThiefSmokeParameterDefaults::GetSmokeBoundsExtent()))
	, RenderBoundsExtent(GetDefaultRenderBoundsExtent())
	, ClusterId(INDEX_NONE)
	, ClusterSourceCount(1)
	, DurationSeconds(TimeThiefSmokeParameterDefaults::SmokeDuration)
{
}
